### ISSUE TITLE
Variants always returning as disabled

### ISSUE THREAD

**Issue by MOPineyro** [Unleash/unleash-edge#216]
### Describe the bug

When making a request to the edge proxy it always returns toggle variants as disabled.

Request:
```
curl --request GET \
  --url 'https://${EDGE_PROXY_URL}/api/proxy?' \
  --header 'Authorization: *:default.4c2b523a32062c335c7d06e9b60f8890a85b417e4ac1xX70c9e64d34' \
  --header 'Content-Type: application/json'
```

Response:
```
{
    "name": "home_screen_banner",
    "enabled": true,
    "variant": {
        "name": "disabled",
        "enabled": false,
        "payload": null
    },
    "impression_data": false
}
```

If I make the same call to the original proxy it returns the correct variant.

Request:
```
curl --request GET \
  --url 'https://${OLD_PROXY_URL}/proxy' \
  --header 'Authorization: some_secret' \
  --header 'Content-Type: application/json'
```

Response:

```
{
    "name": "home_screen_banner",
    "enabled": true,
    "variant": {
        "name": "betr-staging",
        "payload": {
            "type": "json",
            "value": "{\n   \"show\":true,\n   \"show_until\":\"2024-10-30T01:00:00-04:00\",\n   \"image_url\":\"https://promos.betr.app/images/banner_two.png\",\n   \"link_url\": \"https://promos.betr.app\",\n   \"bg_color\":\"#171819\",\n   \"id\":\"betr_oh_launch\"\n}"
        },
        "enabled": true
    },
    "impressionData": false
}
```

The only difference I have between these instances is the key used. For the original proxy, I am using the old key format of 'some_key'. While in the edge proxy, I  am using the latest format, e.g. '*:default.1234...'.

The variant is enabled for all of my environments.

### Steps to reproduce the bug

1. **Adding a feature toggle:**

    - Open the Unleash admin UI.
    - Navigate to the "Feature toggles" tab.
    - Click on the "Create a feature toggle" button.
    - Enter the name of the feature toggle as 'home_screen_banner'.
    - Save the new feature toggle.

2. **Adding a variant to the feature toggle:**

    - In the list of feature toggles, find 'home_screen_banner' and click on it.
    - Navigate to the "Variants" tab.
    - Click on the "Add variant" button.
    - In the payload section, select 'json' as the type and enter the value as shown in your original proxy response.
    - Save the new variant.

3. **Enabling the feature toggle and variant for the default environment:**

    - Navigate back to the "Feature toggles" list.
    - Find 'home_screen_banner' and enable it for the default environment.

4. **Pinging the Endpoints:**

    - Make a request to the edge proxy and original proxy using the respective URLs and headers.
    - For the original proxy, use the older key format as the value for the 'Authorization' header. For the edge proxy, use the latest key format.

### Expected behavior

Edge proxy returns the correct variant.

### Additional context

Edge Proxy Version 7.0.0

### Unleash version

5.1.8

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by sighphyre** [comment]
Okay, interesting. I cannot reproduce this. I'm starting Edge with

```bash
./unleash-edge edge -u http://localhost:4242 -t *:default.186f23153a5eceb8d336b33d895563462e68ed1c87b33038187ad599 //Some **client token** generated in the Unleash UI
```

And then the cURL request:

```bash
curl --request GET   --url 'http://localhost:3063/api/proxy?'   
--header 'Authorization: *:default.96f357c208b033f81c6ef5a227a4f0d3f437cd2b56f40f681ff1d970'  //some **frontend token** generated in the Unleash UI
--header 'Content-Type: application/json'
```

Which does return the correct response with the variant enabled and the correct payload.

Just checking here that you have a Variant correctly bound to the default environment. You should see something like:

![image](https://github.com/Unleash/unleash-edge/assets/22521265/70aaf059-b1ed-48f8-90ce-a2e27bd80ebf)

The old Proxy had a bug where it would return the first variant found in *any* environment if it was pointed at the default environment but that was definitely a bug, Edge won't do that, you'll get a disabled variant back if the variant config is wrong.

**Comment by MOPineyro** [comment]
Below is what I have configured under variants:

![Screen Shot 2023-06-26 at 2 41 41 PM](https://github.com/Unleash/unleash-edge/assets/1578541/a7d4cfa2-16af-47d9-8e32-df7d8383163b)

**Comment by MOPineyro** [comment]
Even the playground returns the correct variant, nothing from the edge proxy using:
https://${EDGE_PROXY_URL}/api/proxy

<img width="1246" alt="Screen Shot 2023-06-26 at 2 56 52 PM" src="https://github.com/Unleash/unleash-edge/assets/1578541/a2eaaadc-0ca9-4042-905a-9600b8993f0a">

**Comment by MOPineyro** [comment]
For further context, I've deployed the Edge Proxy and latest version of Unleash using the official charts: https://github.com/Unleash/helm-charts

**Comment by MOPineyro** [comment]
Hey @sighphyre yes, we've been using Unleash since the pre 4.12 days. Could this be a factor? 

Any advice on the best way to resolve this? Would love to start using the edge proxy but until I can figure out a resolution for this variants issue we're stuck.

**Comment by sighphyre** [comment]
Oh, it's possible that something in the migrations has caused something super weird in your current setup. We don't see a lot of folks still using the default environment anymore and it was always a special case. It shouldn't be that but honestly I'm so confused. I can try spin up 4.12 and migrate up to latest and see if I can reproduce this.

Does this happen on any other environment? Would you be able to setup a development token and a variant on the development environment and share the responses from `api/client/features` and `api/proxy` just for that single toggle?

**Comment by sighphyre** [comment]
@MOPineyro Any idea what your original version of Unleash was? Anything that's old enough to still have the default environment is definitely much older than 4.12 (I suspect you folks were originally somewhere in the 3.x range but a minor version number would be super helpful here)

**Comment by MOPineyro** [comment]
@sighphyre We upgraded and migrated toggles a few times since version 4.4.4, using the official chart - https://github.com/Unleash/helm-charts

**Comment by sighphyre** [comment]
Hey @MOPineyro, we never managed to reproduce this one on our side or get any insight into it. I think we have to close this one, since I don't think we can move forward without steps to reproduce this. If you get steps to reproduce this on a fresh install, please feel free to reopen with more information.
